main = "index.js"
name = "anisq-server"

# Enable domain
route = { pattern = "anisq.iipython.dev", custom_domain = true }

# Prevent Cloudflare from being annoying
workers_dev = false
send_metrics = false

# Compat date and enable node support
# Consumet still piggybacks on crypto for some reason
compatibility_date = "2024-11-10"
compatibility_flags = [ "nodejs_compat" ]
